reach/reach-ui

- packages/window-size/src/index.js
Simple fix for unintentionally calling `addEventListener` inside `removeEvent`.
> Fix memory leak with event handler in WindowSize component.

- www/src/pages/menu-button.mdx
Links to styling were broken. Now, they are not
> Fixed broken links in menu-button.mdx

- www/src/components/createMediaListener.js
It is obvious here that 'transientListener' is a function type.
> detecting rigor is better.

- packages/utils/src/index.js
Closes #6 
Compiled output:
```
var checkedPkgs = {};
var checkStyles = function checkStyles() {};
if (process.env.NODE_ENV !== "production") {
exports.checkStyles = checkStyles = function checkStyles(pkg) {
if (!(process.env.NODE_ENV !== "production")) return;
// only check once per package
if (checkedPkgs[pkg]) return;
checkedPkgs[pkg] = true;
if (parseInt(window.getComputedStyle(document.body).getPropertyValue("--reach-" + pkg), 10) !== 1) {
console.warn("@reach/" + pkg + " styles not found. If you are using a bundler like webpack or parcel include this in the entry file of your app before any of your own styles:\n\n    import \"@reach/" + pkg + "/styles.css\";\n\n  Otherwise you'll need to include them some other way:\n\n    <link rel=\"stylesheet\" type=\"text/css\" …
```
> Make checkStyles a no-op in production

- packages/alert-dialog/src/index.js
- packages/alert/src/index.js
- packages/component-component/examples/todo-list.example.js
- packages/menu-button/src/index.js
- packages/portal/src/index.js
- packages/utils/src/lib/IdContext.js
react-dom does not use named exports and when rollup attempts to bundle
these files it gives the following error:
```
[!] Error: 'render' is not exported by ../../node_modules/react-dom/index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
node_modules/@reach/alert/es/index.js (19:9)
17:
18: import React from "react";
19: import { render } from "react-dom";
^
20: import Component from "@reach/component-component";
21: import VisuallyHidden from "@reach/visually-hidden";
```
> fix react-dom imports

- packages/menu-button/src/index.js
Adds handling for the menu colliding at the bottom, and colliding the right and the bottom. 
Let me know if you have any feedback or if I should add any examples or tests. 
Thanks for taking the time to review! 
**Bottom**
**Right (already included)**
**Right and Bottom**
> Handle menu collision at bottom, and at bottom and right

- packages/window-size/src/index.js
- www/src/pages/window-size.mdx
Tiny PR but takes us further forward with our goal to add `propTypes` to every Reach component :+1:
Helps close: #35
> Add propTypes to `WindowSize` component

- packages/visually-hidden/src/index.js
TODO comment in VisuallyHidden asking for a SkipNav component to be
made. This has since been done but the comment wasn't removed
> Remove redundant comment from VisuallyHidden

- packages/alert-dialog/src/index.js
- packages/dialog/src/index.js
- packages/rect/examples/basic.example.js
- packages/rect/examples/pin.example.js
- packages/window-size/src/index.js
A small help towards the ongoing work in #35.
Also fixes warning that show up in the Rect examples.
> Add PropTypes for AlertDialog, Dialog, and WindowSize; fix warnings in Rect example

- www/src/pages/skip-nav.mdx
Just found a small typo in the documentation for the skip-nav component.
(Thanks for this great repo btw :+1:)
> docs: fix skip nav css selector

- packages/menu-button/src/index.js
`MenuListImpl` contains `ref && ref(node)`, so I think the intention was to allow users to pass in a ref to the wrapping div.
The `React.forwardRef` is missing on the `MenuList` component.
> Add missing forwardRef for MenuList

- shared/build-package.js
Hello!
First of all I want to say thank you for this wonderful repository!
After seeing it I wanted to contribute and help but unfortunately it was impossible on Windows since (AFAIK) `process.env.PWD` isn't set and I was receiving `undefined` value and I was unable to build packages locally.
If `process.env.PWD` is not set, we fallback to `process.cwd()` now.
Cheers
PS. 
Not sure about changes in `yarn.lock` I just installed dependencies 😕
> Fixed building packages on Windows

- packages/dialog/examples/autofocus.example.js
- packages/dialog/examples/dropdown.example.js
- packages/dialog/examples/nested.example.js
- packages/dialog/package.json
- packages/dialog/src/index.js
- packages/dialog/yarn.lock
- yarn.lock
React-Focus-Lock fixes:
- #83, it accepts _focus_ events via React Event System, thus count portaled content as own content.
- unreported issue about nested dialogs. Once second dialog is closed lock is no more active.
- `initialFocusRef` was not drilled to Dialog
Scroll-Lock(react-remove-scroll) fixes:
- #98, `position:fixed` elements have to disable body scroll on iOS
- unreported issue, alerts and modals should lock scroll(by design).
- also support portals, nested locks and so on
+ a bit simpler code about focus management
+ a few examples to prove/test new stuff
> Add react-focus-lock and react-remove-scroll

- packages/portal/src/index.js
This afternoon I tried plugging the `MenuButton` component into the new React DevTools (https://github.com/bvaughn/react-devtools-experimental/pull/108) but I ran into a snag. The DevTools extension portals itself into Chrome panels, but the Reach `Portal` component assumes its content should be appended to the root/original `document`. The result is that the `MenuButton` portal (and others) are essentially invisible.
This PR fixes that. Posting for discussion purposes! 🙇
cc @ryanflorence
> Append portaled content to the correct (owner) document

- packages/tooltip/src/index.js
Given #166, there is an issue of new Tooltips being shown by default if the current global state happens to be true for any other Tooltip (as there is a single state container for ALL Tooltips in an application).
This patch addresses that problem by only recovering the global state if the ID of the new usage of `useTooltip` has the same ID as the currently active ID.
However, #166's use case does still present an interesting issue, even after this patch. Having the default state be based on the ID of the Tooltip can lead to false positives as IDs are reused within the life of the the Application. Meaning that Tooltips that aren't actually meant to be shown as active appear as active. Although, this may be better to file as a separate issue.
> prevent all tooltips from showing initially based on global state

- www/src/pages/styling.mdx
This commit adds a note about how you can remove the warning of a missing CSS file, if you want to implement the required styles yourself.
Fixes #244
> Add note about removing CSS warning

- packages/visually-hidden/src/index.js
At the moment `VisuallyHidden` shows up in the React dev tools as `Anonymous` and in snapshot tests as `Component`, but by making it a named function it'll just say `VisuallyHidden`. 👍
> VisuallyHidden: Use a named function so it has a display name 

- packages/tabs/src/index.js
I am currently using the tabs component and noticed that if I conditionally render a child inside <Tabs> the following error occurs when the conditional returns false:
`Cannot read property 'type' of null`
This only happens when I conditionally render using the '&&' operator.
example:
```
<Tabs> 
{someCondition && <div />}
<Tabs>
```
> fixing null children issue

- packages/alert/package.json
- packages/auto-id/package.json
- packages/popover/package.json
- packages/portal/package.json
- packages/rect/package.json
- packages/skip-nav/package.json
- packages/tabs/package.json
- packages/tooltip/package.json
- packages/utils/package.json
- packages/visually-hidden/package.json
- packages/window-size/package.json
Our site likes to [credit authors whose works are used](https://observablehq.com/open-source), and unfortunately reach/portal and reach/rect, which we use, have blank author fields. This PR sets all author fields for all reach-ui packages to `"Ryan Florence <@ryanflorence>"`, which was the value for the ones that were filled out before.
> Set author fields to uniform value

- packages/alert-dialog/package.json
- packages/alert/package.json
- packages/combobox/package.json
- packages/component-component/package.json
- packages/dialog/package.json
- packages/menu-button/package.json
- packages/rect/package.json
- packages/tabs/package.json
- packages/tooltip/package.json
- packages/window-size/package.json
Reverts reach/reach-ui#254
I mistakenly merged #254. prop-types are not a peer dep. They are a regular dep that gets stripped out in production.
> Revert "add missing peer deps and use a more forgiving range"

- www/src/pages/tabs.mdx
Fixes a typo found in the "Tab isSelected" section of the "Tabs" docs
> docs(tabs): fix typo in tab isselected section

- packages/menu-button/src/index.js
This PR fixes conditionally-rendered menu items causing crashes when MenuList attempts to focus null children. Issue resolved by passing children through Children.toArray, which filters out null elements. 
Resolves #121
> Fix conditionally-rendered MenuItem in MenuList

- packages/menu-button/src/index.js
This is a fix for the [issue #100 ](https://github.com/reach/reach-ui/issues/99).
1. Stop the default behavior i.e. scrolling.
2. Select the current item.
> Menu button space fix

- packages/menu-button/src/index.js
Fixes #94 
This PR fixes a couple of critical issues on IE11:
IE11 and below don't support `window.scrollX` and `window.scrollY` which results in `top: NaNpx` and same for `left`
The fix implemented is changing to `window.pageXOffset` and `window.pageYOffset` which are supported by all browsers. [Read more](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX#Notes)
**After fix:**
IE11 and below don't support `event.relatedTarget` which results in the `onBlur` check failing incorrectly.
The fix implemented was simply to also check for `document.activeElement` too. [Read more](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement)
**After fix:**
> @reach/menu-button: Fix positioning and hovering issues on IE11

- www/src/pages/auto-id.mdx
Right now there's an `Auto ID` menu at https://ui.reach.tech/, which will lead to https://ui.reach.tech/auto-id, and show the `NOT FOUND` page.
This PR adds a page for `Auto ID` (`@reach/auto-id`) and fix that issue.
> Fix missing Auto ID page on documentation website

- packages/auto-id/index.d.ts
Nothing fancy going on here!
I'd just love to be able to use this package in a typescript project without writing a separate typedef.  :)
> Declare type definition for @reach/auto-id

- packages/dialog/src/index.js
- packages/rect/examples/use-rect.example.js
- packages/tabs/examples/disabled.example.js
I figured this was a good solution to allowing the user to conditionally invoke their dismiss prop depending on the event type that called onDismiss.  
e.g. only invoke your dismiss prop for event.type === 'keydown'
Let me know if I missed anywhere, or if I should update any examples in addition.
- Adds event as a param from onClick and onKeyDown to onDismiss callback in DialogOverlay
- Removed unused ref Rect in use-rect.exmaple
- Removed unused ref useState in disabled.example
The removal of the unused refs might be a problem with setup? it looks like in www/.eslintignore it tries to ignore ../packages. But I could not pass the --max-warnings=0 check on pre-commit without removing them.
> Adding the html event (onClick or onKeyDown) as a param to DialogOverlay onDismiss

- packages/dialog/src/index.js
This PR covers the same ground as #239, but uses the Component² abstraction for refs.
> [dialog] Only close the dialog if the click outside originated outside

- packages/dialog/examples/dropdown.example.js
- packages/menu-button/examples/with-tooltip.example.js
- packages/tooltip/examples/animated.example.js
When attempting to build storybook to confirm the IE 11 fix in #205, I encountered some issues.
Fixes
- Unavailable module error when building storybook examples
- Pulls in CommonJS build of React Spring for IE11 support
> Fix to allow storybook build and view in IE11

- www/src/pages/alert-dialog.mdx
- www/src/pages/alert.mdx
- www/src/pages/combobox.mdx
- www/src/pages/dialog.mdx
- www/src/pages/funding.mdx
- www/src/pages/index.mdx
- www/src/pages/menu-button.mdx
- www/src/pages/rect.mdx
- www/src/pages/skip-nav.mdx
- www/src/pages/styling.mdx
- www/src/pages/tabs.mdx
This pull request goes through all the different docs, and does the following:
- removes usage of component-component in favor of function components with hooks
- refactors class component examples to use function components and hooks
- standardize all example component names to `Example`
- Fix a few typos, broken links and what not
Fixes #269
> Update docs to use hooks

- packages/menu-button/examples/basic.example.js
- packages/menu-button/src/index.js
> MenuButton: Allow user to set MenuButton ID

- packages/menu-button/src/index.js
`@reach/menu-button` has an odd behaviour when the `MenuButton` and/or `MenuList` are wide. See the bug in action:
<details>
<summary>GIF</summary>
</details>
In (other) words, when the list is wider than the button the layout algorithm always assumes that a collision with the left side has occured. This works fine for left aligned menus, but not so much for right aligned ones. Since the list is not wider than the viewport there is enough space to expand it to the left.
Sandboxes are worth 1000 words, so I created [this one][sandbox] to play around in.
[sandbox]: https://codesandbox.io/s/misty-darkness-zjepf
> Handle left collision with a wide MenuList

- packages/tooltip/examples/triangle.example.js
Okay, this might seem kinda dumb but a common thing with tooltips in my experience: on platforms where scrollbars are visible the tooltip causes scrollbars to appear if the tooltip is too close to the said scrollbar:
Deducting the [common max of scrollbar widths](https://codepen.io/sambible/post/browser-scrollbar-widths) from `maxLeft` removes the issue:
And the tooltips that don't touch the scrollbar still work as expected:
> Account for possible scrollbars in the Tooltip triangle sample

- www/src/pages/portal.mdx
This pull request fixes a typo on the Portal docs page where the documentation mentions WindowSize when importing instead of Portal (but the example earlier on the page uses `<Portal>`).
> Fix typo in Portal docs page (WindowSize -> Portal)

- packages/dialog/src/index.js
- packages/slider/src/index.js
> Exclude Slider + Dialog propType declarations in prod

- packages/slider/examples/vertical.example.js
- packages/slider/examples/with-steps.example.js
- packages/slider/src/index.js
So people can use a constant instead of e.g. the string "vertical".
> Export Slider* constants for use in user code

- packages/menu-button/src/index.js
This presents a non-breaking alternative solution to https://github.com/reach/reach-ui/pull/148. Props passed to the `Menu` component will be passed through to the outer `reach-menu` that is rendered in the portal when the menu is visible.
> MenuButton: accept pass-through props on outer menu component

- packages/tooltip/examples/with-dialog.example.js
- packages/tooltip/src/index.js
Also, added another example with tooltips rendering inside a modal to try to replicate more closely the bug described by @bvaughn in #193.
Note: It was suggested in #193 that the bug was in the auto-id package since it provides `null` ids on the initial render. According to @ryanflorence this behavior is intentional. auto-id is not supposed to provide ids on the initial render because of the non-deterministic nature of server-rendered apps. Instead, they are supposed to be applied only _after_ the initial render, to be used by screen readers.
Fixes #193
Closes #293
> Fix tooltips flicker

- website/src/pages/styling.mdx
This pull request updates documentation or example code.
The additional information will hopefully help people to find the solution faster than searching in the Github issues.
---
related to https://github.com/reach/reach-ui/issues/136
> Add solution to ignore css warning in jest tests

- packages/alert-dialog/src/index.js
Adding this in its own PR, because it _could_ be treated as a breaking change? It's a small typo on `<DialogContent>`, but if a user is using that data attribute for styling, fixing the typo could result in breaking that user's styles.
> Fix data attribute typo in alert dialog

- packages/combobox/src/index.js
Not sure if this is an actual issue, but https://github.com/kentcdodds/stop-runaway-react-effects is throwing for these as they run on each render.
I figure it doesn't hurt to have them only fire when needed?
> useLayoutEffect deps

- packages/tooltip/index.d.ts
The types shipped with the tooltip result in 
`A 'declare' modifier cannot be used in an already ambient context.`
Removing the nested `declare` fixed the above error.
> Fix Tooltip TypeScript definition

- packages/dialog/examples/change-styles.example.js
- website/src/pages/animation.mdx
- website/src/pages/dialog.mdx
---
Hi! 
First PR to this repo, hope it helps.
**What:**
This PR updates (& fixes) examples on the website and storybook that uses transform/translate3d values and `react-spring`. When using `transform` you have to use the `interpolate` function rather than setting the value directly with css, or the transform style will be ignored.
**How to verify:**
Test the animated dialog example or the "Change styles" dialog example in storybook. With this fix, the transform should work (in master these examples just animate opacity, not transform).
**HELP**
I'm not sure why `website/yarn.lock` updated, I assume it wasn't up to date with the …
> Fix examples using animated translate values

- packages/visually-hidden/src/index.js
Refer to SO question: https://stackoverflow.com/questions/12982269/is-it-semantically-incorrect-to-put-a-div-or-span-inside-of-a-button/12982334
> Make visually hidden render as span

- packages/tooltip/index.d.ts
Export `TooltipPopup` from type definition.
resolves #351 
> Fix @reach/tooltip type definition

- packages/dialog/index.d.ts
Attempting to use the `allowPinchZoom` prop on `<DialogOverlay>` results in the following TypeScript error:
> Property 'allowPinchZoom' does not exist on type [...]
> [@reach/dialog] add `allowPinchZoom` prop to TypeScript definition

- packages/utils/package.json
I started using this package at work and noticed that the types exist here but aren't being published to npm with the package. If they were intentionally left out, feel free to close this. If it was an accident, I believe this should do the trick.
Thanks!
> Include @reach/utils types when publishing to npm

- packages/alert-dialog/src/index.js
- packages/auto-id/index.d.ts
- packages/auto-id/src/index.js
- packages/combobox/src/index.js
- packages/slider/src/index.js
- packages/tabs/src/__snapshots__/index.test.js.snap
- packages/tabs/src/index.js
- packages/tooltip/src/index.js
- website/src/pages/auto-id.mdx
- website/src/pages/dialog.mdx
The general approach here boils down to this: anywhere we are generating a UID with `useId`, we need to give the developer a way to pass a ID prop into the top-level component as an alternative. This will be used as a root ID string so that all descendant component IDs will be deterministic.
We may still choose to, eventually, allow nested component IDs to be passed directly, but at the moment this adds more complexity than it's worth. So long as a user can specify a root ID, they should be able to do whatever they want with children.
> Accept ID as prop to fix deterministic ID issues

- packages/alert-dialog/src/index.js
- packages/alert/src/index.js
- packages/combobox/src/index.js
- packages/component-component/src/index.js
- packages/dialog/src/index.js
- packages/menu-button/src/index.js
- packages/rect/src/index.js
- packages/slider/src/index.js
- packages/tabs/src/index.js
- packages/tooltip/src/index.js
- packages/window-size/src/index.js
Fixes #375 
This PR fixes how the `prop-types` package is imported into various files. This project was attempting to destructure the import like: `import {node, func} from 'prop-types'` but the `prop-types` package does not export individual modules like that. This causes problems with bundlers like rollup.
> multiple packages: fix how prop-types is imported (fixes #375)

- packages/visually-hidden/src/index.js
Added guards in `visually-hidden` to deal with potential issues related to word wrapping. Reference article here: https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe
Went ahead and removed `display: block` since we're using `position: absolute` as well, per #372.
> visually-hidden: Add guard for word wrapping

- packages/tooltip/src/index.js
Description
By definition, statecharts ignore events for which they don't have defined transitions on the active state node. So it seems to me this is counterproductive to guard against "undefined" transitions at the event dispatch site. The main reason for that is that whenever you want to tweak your statechart definition you'd have to tweak your transition call sites too
This was previously submitted as https://github.com/reach/reach-ui/pull/176 but that PR got closed because of housekeeping purposes. I still believe this change is valid and beneficial, so I'm resubmitting this.
> [@reach/tooltip] Simplify Tooltip statechart management

- packages/tooltip/src/index.js
This PR addresses https://github.com/reach/reach-ui/issues/202. We move the event listener to the document so escaping at any point will dismiss the tooltip.
> tooltip: add document event listener to hide tooltip on escape

- packages/tooltip/index.d.ts
Currently `ref` is required when calling the `useTooltip` hook. This shouldn't be the case, since `useTooltip` has its own internal ref, if not provided.
Related error:
> [Tooltip] Make `ref` optional on `useTooltip` hook types

- website/src/pages/alert-dialog.mdx
Fixes a mismatched closing tag in the docs for `<AlertDialog />`.
> docs(alert-dialog): Fix mismatched closing tag in example

- packages/alert-dialog/package.json
- packages/alert/package.json
- packages/auto-id/package.json
- packages/combobox/package.json
- packages/component-component/package.json
- packages/dialog/package.json
- packages/menu-button/package.json
- packages/popover/package.json
- packages/portal/package.json
- packages/rect/package.json
- packages/skip-nav/package.json
- packages/slider/package.json
- packages/tabs/package.json
- packages/tooltip/package.json
- packages/utils/package.json
- packages/visually-hidden/package.json
- packages/window-size/package.json
It will add repo link on NPM and allow bots to get more informations about that packages (i.e. dependabot, renovate...)
When using dependabot, it will correctly find the packages repository and add link with a list of commits/releases inside the dependabot PR. 
Currently, we just have a text with the name of the packages to be updated:
> [all] Add repository infos to packages manifest

- packages/menu-button/src/index.tsx
Right now, when using `disabled` (a valid HTML attribute) on `MenuButton`, would error in TypeScript as:
```
Property 'disabled' does not exist on type 'IntrinsicAttributes & HTMLAttributes<HTMLButtonElement> & { children: ReactNode; } & RefAttributes<HTMLButtonElement>'.
<MenuButton className={styles.select} disabled={disabled} onClick={onOpen} {...rest}>
```
> [menu-button] Use React.ButtonHTMLAttributes for types

- packages/utils/src/types.tsx
This PR removes `as` as mandatory prop of components that wrapped with `ComponentWithAs` 
fixes #427 
> [Utils] Remove the mandatory of "as" type

- packages/menu-button/src/index.tsx
Since https://github.com/reach/reach-ui/commit/7407794c58fac136ba67c5f009782d30c2f9020d  it is disallowed to pass the style property to the `<MenuPopover />` component in the `@reach/menu-button` package. I couldn't figure out any specific reason for this change.
> Allow passing the style property to MenuPopover again.

- packages/alert-dialog/src/index.tsx
- packages/alert/src/index.tsx
- packages/dialog/src/index.tsx
- packages/menu-button/src/index.tsx
- packages/tabs/src/index.tsx
- packages/tooltip/src/index.tsx
- packages/utils/src/index.tsx
The inspiration for these changes [was this tweet](https://twitter.com/chancethedev/status/1218399362746933248) 😅. I didn't see any contributing guidelines _(I could've missed them)_ so I wasn't confident if it was necessary to do a PR per package? If that's the case, I'm happy to separate out these changes!
I searched for `as any` in the codebase and attempted to resolve most of the more straightforward ones. There are a few more but those will likely be much more involved. 
There were a few types of changes:
- Converted the prop types `() => {}` to `() => null` to comply with their type definitions. [They expect either `Error` or …
> [Several Packages] Remove several type casts

- packages/alert/src/index.tsx
Using Typescript we wasn't able to pass props to the `Alert` component to be spread into the nested div (useful for style, className, ...).
> [alert] Fix spread typing

- website/src/pages/rect.mdx
[`useRect` returns `null`](https://github.com/reach/reach-ui/blob/master/packages/rect/src/index.tsx#L94) rather than `undefined` on the first render.  I suppose a library consumer could get tripped up assuming it was `undefined` and write something like `if (typeof rect === 'object') rect.width` which would throw an error when `rect` is `null`.
> docs(rect): update first render return value

- packages/menu-button/src/index.tsx
Render phase work like useReducer functions can be called more than once in concurrent mode which makes them unsuitable for performing side effects. [Strict Mode](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) always double invokes them to help catch these issues.
This PR should fix #440 by moving the focus and callback calls into the event handler, which does not get double invoked in concurrent / StrictMode.
> [Menu-Button] Fix double-invoking onSelect in StrictMode

- packages/dialog/examples/basic-ts.example.tsx
- packages/dialog/examples/basic.example.js
- packages/dialog/src/index.tsx
When passing `allowPinchZoom` to `Dialog` as per the docs, the prop is not passed on to `DialogOverlay`, instead it's spread onto `DialogContent` and then on to the DOM, causing a development warning from ReactDOM (`React does not recognize the `allowPinchZoom` prop...`).
This PR instead passes it on to `DialogContent`, which I assume is the intended behaviour. Didn't add any tests but did add it to the `Basic` storybook example to verify the fix. Also tested it with my own app.
---
> [@reach/dialog] Pass `allowPinchZoom` prop from Dialog to DialogOverlay

- website/src/pages/menu-button.mdx
Spent a few minutes not understanding why I could not prevent the event when using onClick ;)
-------------------------
> [docs] Fix glitch: MenuButton uses onMouseDown prop instead on onClick

- packages/combobox/src/index.tsx
The use of the private type was replaced by `Partial<PopoverProps>` in 628790f. I don't believe the type is necessary as a named export any more. However, because it was a named export, removal of this type should likely be considered part of a breaking change update to the package in case any consumer was relying on the type.
> [Combobox] Remove unused __ComboboxPopoverProps type

- website/src/pages/animation.mdx
- website/src/pages/dialog.mdx
Hi there, my first PR ever :) So I copy and pasted an animation example from your website that caused me a good hour of hair pulling and the reason was, an animation _inside_ the animated dialog wasn’t working. The cause was that the AnimatedDialogOverlay and AnimatedDialogContent were being recreated on every render because of using the animated HOC inside the render. Hopefully this small docs fix will help future users of the library.
Thanks.
ps. sorry for the extra commits, I was editing this in the Github editor 😅
> Docs: fix animation examples to not use HOCs in the render

- packages/combobox/__tests__/__snapshots__/combobox.test.tsx.snap
- packages/combobox/src/index.tsx
[Use ARIA 1.2 spec for combobox][4]
The [ARIA 1.1 spec for combobox][6] (used in Reach right now … kind of *) was meant to solve a structural pitfall of ARIA 1.0, but ended up introducing a whole set of [new problems][1] in the wake. The 1.1 implementation is quite broken for VoiceOver.
In a study done in 12/2019, [ARIA 1.2 is less buggy across board compared to ARIA 1.1][2]. The author of this study, Sarah Higley, is on the accessibility working group within the W3C, and after a colleague spoke with her recently (cc: @backwardok) she recommended moving forward with the 1.2 spec given its better effective support by browsers and screen readers.
\* Reach currently mixes ARIA 1.1 and ARIA 1.2, given that it [includes `aria-controls` on the input itself][5]—despite that not being part of the …
> [Combobox] Use ARIA 1.2 spec

- packages/listbox/src/index.tsx
- website/src/pages/listbox.mdx
This PR addresses #512 by providing an `expanded` field in the object passed to ListboxInput's render function. I matched the naming convention already present for ListboxButton's render function. I also updated the docs where using the component in this way is mentioned.
> [Listbox]: add expanded value for ListboxInput render function

- packages/combobox/package.json
- packages/combobox/src/index.tsx
- yarn.lock
The [escape-regexp package](https://github.com/component/escape-regexp) fails approval when trying to detect the license under which the project is distributed.
The package has not been touched in 7 years, and implements a single-line function that can be copied directly into source.
---
> [Combobox] Remove escape-regexp dependency

- packages/combobox/examples/using-popover-visibility-hook.example.tsx
- packages/combobox/src/index.tsx
Influenced by the [Reach UI Philosophy][1] on exposing state for JS styling, and by the [recent addition of useTabsContext][2].
```jsx
const StyledComboboxInput = (props) => {
const { isExpanded } = useComboboxContext();
return (
<ComboboxInput
{...props}
style={{ backgroundColor: isExpanded ? "blue" : "red" }}
/>
);
};
```
The real-world desire for this feature comes from a design I received that changes the inputs bottom border radii when the popover is open. You can see I tried to implement it based on input focus and value change, but this doesn't handle every case and adds unnecessary state and complexity.
Before hook
After hook
---
[1]: https://gist.github.com/ryanflorence/e5c794e6093d16a69fa88d2112a292f7#exposing-state-for-js-styling
[2]: …
> [Combobox] Add popover visibility hook for styling

- website/src/pages/rect.mdx
Just noticed that the `props` links did not match the markdown-generated URLs for the docs of `@reach/rect`
> Docs: Fix Rect-Props hrefs

- packages/combobox/__tests__/combobox.test.tsx
- packages/combobox/examples/basic-ts.example.tsx
- packages/combobox/examples/basic.example.js
- packages/combobox/examples/controlled-ts.example.tsx
- packages/combobox/examples/controlled.example.js
- packages/combobox/examples/lots-of-elements.example.js
- packages/combobox/examples/no-popover.example.js
- packages/combobox/examples/open-on-focus.example.js
- packages/combobox/examples/token-input.js
- packages/combobox/examples/with-button.example.js
- packages/combobox/src/index.tsx
- website/src/pages/combobox.mdx
> "If the combobox has a visible label and the combobox element is an HTML element that can be labelled using the HTML label element (e.g., the input element), it is labeled using the label element. Otherwise, if it has a visible label, the combobox element has aria-labelledby set to a value that refers to the labelling element. Otherwise, the combobox element has a label provided by aria-label." [source][1]
Given the number of ways to label the combobox, we cannot enforce or handle the aria programmatically. Outside of a runtime check, the best we can do is set good examples with proper labeling.
[1]: https://www.w3.org/TR/wai-aria-practices-1.2/#wai-aria-roles-states-and-properties-6
Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help …
> [Combobox] Add aria-label to examples

- packages/popover/src/index.tsx
- Adds helper `positionRight` to set default alignment
of popover to the right
- Create `getTopPosition` abstraction since same logic
is now used in 3 places
> Add positionRight helper to Popover

- packages/combobox/src/index.tsx
**Before**
Typing in the input, tabbing to an interactive element in the listbox, focusing the input again, then attempting to delete the entire input value with <kbd>⌘</kbd> + <kbd>⌫</kbd> ("command + backspace" on macOS) is a noop for the input value. Notice that the controlled value is updated properly.
**After**
Same sequence as above works as expected—the value is properly cleared on <kbd>⌘</kbd> + <kbd>⌫</kbd>.
---
> [Combobox] Clear value when input focused after interacting with popover

- packages/menu-button/__tests__/menu-button.test.tsx
- packages/menu-button/src/index.tsx
Fixes #507 
Notably, this changes two tests for `menu-button`, as they relied on the old behaviour, just clicking the button and firing a `keyDown`, assuming that would select the first item. Since they were testing usage of Space and Enter respectively, I made them use those respective buttons to open the menu, which still does automatically focus the first item.
---
> [MenuButton] Don't default to focusing a MenuItem when using mouse

- packages/utils/package.json
The `warning` utils exposes the types for the `warning` package so it `@types/` should be a dependency as well.
> add missing type dep

- packages/portal/src/index.tsx
Fixes #557 
This is just a simple fix for this bug. I verified that it fixed the bug and that hot-reloading now works without errors.
----------------
> portal: fix TypeError when using hot-loader

- packages/listbox/__tests__/listbox.test.tsx
- packages/listbox/src/index.tsx
This PR fixes #569.
**Listbox** is not hiding the generated `input`. But documentation and tests indicate the rendered `input` is hidden. 
- This PR hides it by making it `type="hidden"`.
- Unit tests have been updated to ensure the input is hidden.
- No storybook was added because this is a bug fix. The change does hide the input that used to be visible in the `With a Form` storybook.
---
> [Listbox] Hide input that documentation claims is hidden

- packages/tabs/__tests__/tabs.test.tsx
- packages/tabs/src/index.tsx
This PR fixes https://github.com/reach/reach-ui/issues/165, it was first fixed in https://github.com/reach/reach-ui/commit/5f75dd525385fc2d800205ff99dae205a1bce6b4 but then broken in https://github.com/reach/reach-ui/commit/a2ab2be8b0ca122e3fa03a00e24d78b757b48e35.
I've added a couple of tests but I'm not sure if they're what you expect so feedback is welcome!
_________
> Use type button by default in Tab component

- scripts/build.ts
- scripts/utils.ts
<hr />
Closes #586
I figured it's probably more straightforward to just drop `Array.flatMap` for now. We could instead check for `'flatMap' in Array` as well, but I don't see the point.
> fix(build): dont use `Array.flatMap`

- website/src/styles/app.scss
> fix(website): remove redundant :root selector in app.scss of website

- README.md
The route of link https://yarnpkg.com/docs/install does not exist anymore and has been changed to https://yarnpkg.com/getting-started/install, I have updated the new route in the README.md
Opening the current route takes to the NOT FOUND page.
> docs: updated the README.md with new link of yarn install instructions

- website/package.json
- website/yarn.lock
<hr />
Closes #598
So I don't know since when did the examples get broken, but I tracked this down to a issue with Gatsby: https://github.com/gatsbyjs/gatsby/issues/19827#issuecomment-573986378
What I did was:
- `rm -rf node_modules && rm -rf .cache`
- `yarn remove react react-dom gatsby`
- `yarn add react react-dom gatsby`
And the examples started working again! Gatsby was also bumped by a minor version which I think is fine.
> fix(website): update lock file

- website/src/pages/tabs.mdx
`useRect` is relative to viewport, but absolute positioning is relative to containing block. Compensate by using the difference.
> Fix tabs.mdx animated example

- packages/tabs/src/index.tsx
<hr />
Closes #561
I don't know if this is the correct solution, but it seems to make sense (?) and work.
> fix(tabs): wait for TabPanel to mount before setting `hidden`

- packages/popover/src/index.tsx
When the `targetRef` is the last tabbable element outside the popover, `getElementAfterTrigger` returns the first tabbable element inside the portal causing the focus to stay trapped inside the popover. What we want is for `getElementAfterTrigger` to return an element only if it is not inside the popover.
> [popover] Fix stuck focus

- packages/slider/__tests__/slider.test.tsx
- packages/slider/src/index.tsx
> fix(slider): prevent keyboard events when disabled

- packages/alert/src/index.tsx
- packages/rect/examples/change-observed-ref.example.tsx
- packages/rect/package.json
- packages/rect/src/index.tsx
- packages/utils/src/index.tsx
- yarn.lock
This PR fixes some issues in the rect package.
- The observer should only be initialized and removed when either the DOM node or `observe` prop change.
- The component stores the DOM node in state and updates internally any time that node reference is updated.
> rect: Fix issues with the observer between renders

- packages/menu-button/src/index.tsx
copied from https://github.com/reach/reach-ui/pull/607
As far as I know `.relatedTarget` is always null for mousedown events and the spec seems to confirm that:
https://w3c.github.io/uievents/#event-type-mousedown
> Dont try to use .relatedTarget of the mousedown event

- website/src/pages/accordion.mdx
Just a small typo I found which is causing a link to break. The ID in the anchor should be all lowercase.
> [website] fix typo in anchor link for `useAccordionItemContext`

- packages/tabs/src/index.tsx
This is a bug fix. https://reach.tech/tabs#tabs-children mentions that using a function for children is supported.
> tabs: Fix prop-types for `Tabs` children

- packages/slider/styles.css
Setting the slider to have a width of 350px seems really arbitrary and is almost never what you want. Typically, inputs default to taking up the full width of a container and I don't see why a slider should be any different.
AFAIK the styling that reach-ui ships with is the minimum to make the component functional, and this css rule seems to go against that.
> Remove slider width styling

- packages/utils/src/index.tsx
Fixes: https://github.com/reach/reach-ui/issues/707
> [Utils] export imported types as types

- packages/tooltip/src/index.tsx
This allows users to re-use this logic in their own apps.
In particular, I had a use case where I wanted to change the tooltip offset and the only way I could do so was to copy the definition of the `positionDefault` function.
**Note:** I didn't test this (this PR was made from the web interface), just curious if this is something that would be acceptable. Alternatively (and/or additionally), we could add an `offset` prop to the `Tooltip` component.
> @reach/tooltip: Export `positionTooltip` function

- packages/tooltip/examples/with-disabled-button.example.js
- packages/tooltip/src/index.tsx
----
Thanks for the great library!
This PR fixes https://github.com/reach/reach-ui/issues/231 and https://github.com/reach/reach-ui/issues/564
We use `@reach/tooltip` with disabled buttons and inputs and the need to create a wrapper around such components is rather inconvenient.
Pointer events API is [widely supported](https://caniuse.com/pointer) and PR contains a fallback just in case. 
Unfortunately couldn't update component tests because there is no support in `jsdom` yet https://github.com/jsdom/jsdom/pull/2666, I tried to use the proposed workarounds but they didn't work for me.  So tests actually check that component still …
> fix(tooltip): consistent cross-browser behavior with disabled elements

- packages/combobox/examples/open-on-focus.example.js
The existing `openOnFocus` example mounts/unmounts the popover based on the results array state, which returns null if the input term is an empty string. This is confusing in the context of the `openOnFocus` prop because the popover doesn't show on focus if the input is empty.
An alternative to using hardcoded example options would be to use a variant of `useCityMatch` that returns an array of e.g. the first 10 cities if the input term is an empty string.
> [Combobox] Update openOnFocus example to work even with empty input

- yarn.lock
A fresh clone and install of this library results in a yarn.lock diff
with the `use-throttle` dep removed. This makes sense, as it's not used
anywhere in the source code nor is it a dep of any other dep.
The strange part is why this diff wasn't showing up sooner given that a
[blame][1] shows the most recent change to this part of the lock file
was 7 months ago.
[1]: https://github.com/reach/reach-ui/blame/881b6ee3496c4b5b868f5ca1f706af63ea48114e/yarn.lock#L16431
> Remove unused use-throttle dep from yarn.lock

- packages/menu-button/src/index.tsx
(snipped)
----
I'm using potentially hundreds of menus in my project, and I've noticed that whenever I click anywhere, a lot of React re-renders occurred. With a small number of menus this doesn't matter, though.
This happens because the useReducer callback always returns a fresh object, even if it's deep-equal to the previously returned one. I checked what was being done to prevent re-renders for this reason, and I found many conditionals that check for the current state, and don't call `dispatch` if the state is already correct. So I've done this as well to prevent …
> [menu-button] Prevent extraneous updates when clicking outside closed menus

- packages/accordion/package.json
- packages/alert-dialog/package.json
- packages/alert/package.json
- packages/auto-id/package.json
- packages/checkbox/package.json
- packages/combobox/package.json
- packages/component-component/package.json
- packages/descendants/package.json
- packages/dialog/package.json
- packages/disclosure/package.json
- packages/listbox/package.json
- packages/machine/package.json
- packages/menu-button/package.json
- packages/popover/package.json
- packages/portal/package.json
- packages/rect/package.json
- packages/skip-nav/package.json
- packages/slider/package.json
- packages/tabs/package.json
- packages/tooltip/package.json
- packages/visually-hidden/package.json
- packages/window-size/package.json
This should resolve https://github.com/reach/reach-ui/pull/761#issuecomment-809307675
> Add *.css files to the list of sideEffect(ful) files

- packages/dialog/examples/animated.example.js
- website/src/pages/dialog.mdx
_________________
Fix the issue #669.
> [Dialog] Fix animated dialog warning

- packages/menu-button/src/index.tsx
Fixes #811.  
I found that without preventing the original event's default, I was getting two click events, and one would fire inside a Dialog that I was opening, immediately closing it.  This ensures the original event is prevented when creating a new .click() on a link.
> [menu-button] Prevent default for links to avoid double click events

- packages/menu-button/src/index.tsx
Issue:
Info about the problem here: https://github.com/reach/reach-ui/issues/805
Solution:
`mousemove` event is not being called because of the assistive technology, my suggestion is to use `onfocus` for these cases.
> menu-button(fix): fix selection when assistive tech on

- packages/portal/src/index.tsx
- website/src/pages/portal.mdx
This PR aims to solve the issue #666.
It introduces a new optional prop for Portal: `nodeContainer` that allows the user to specify the containing node to render the Portal in.
If this PR is approved, then we can create a follow up PR to pass this prop to other relevant packages.
---
> Add optional node container target to Portal

- packages/combobox/src/index.tsx
Here's the context. In the existing Storybook, go to combobox controlled (third one). Then repeatedly type in the box, and select something. Occasionally (roughly 1 in 5 times) you'll see the text of the thing you select flash in the input, before being cleared. To make this more pronounced, and easier to see, edit this code:
```js
case SELECT_WITH_CLICK:
return {
...nextState,
value: event.value,
navigationValue: null,
};
```
to this
```js
case SELECT_WITH_CLICK:
return {
...nextState,
value: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
navigationValue: null,
};
```
This PR fixes that, by changing the value to null when the combobox is used in controlled mode. 
--- 
Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help us process your …
> Fix selection for controlled combobox

- packages/listbox/src/machine.ts
Hello, our website has a Listbox within a form. When we press enter on the Listbox, it is currently clicking the first button that it finds on the page and not our submit button.  This PR updates the specificity of the selector to select the first button without a type or the first item with type=submit.
Thank you! 
https://github.com/reach/reach-ui/issues/904
> [ListboxInput]: Update submit button querySelector specificity

- website/src/pages/checkbox.mdx
Hi I saw this little documentation bug when I was looking at the site and thought I'd fix it if it were on github. And here it is! 🎉
Sorry most of the template items I left unchecked, as they are not applicable.
---------
> Docs: escape vertical bar in CustomCheckbox Props table

- website/src/pages/skip-nav.mdx
This PR updates the `SkipNavLink` docs to include the `contentId` prop! It's a super helpful prop and I wanted to make sure folks knew about it. 
- n/a Test the change in your own code (Compile and run).
- n/a Add or edit tests to reflect the change (Run with `yarn test`).
- n/a  Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- n/a Add documentation to support any new features.
> docs: Adds `contentId` to SkipNavLink docs

- packages/popover/src/index.tsx
This PR is mainly fixing this [issue](https://github.com/reach/reach-ui/issues/942). 
Since the popover top position based on the `top` of `targetRect`.  When the page is scrolled, the `top` of `targetRect` is chagned. 
```
function getTopPosition(
targetRect: PRect,
popoverRect: PRect,
isDirectionUp: boolean
) {
return {
top: isDirectionUp
? `${targetRect.top - popoverRect.height + window.pageYOffset}px`
: `${targetRect.top + targetRect.height + window.pageYOffset}px`,
};
}
```
We shouldn't observe the `targetRef` only when popover is shown, otherwise, the top position of popover calculation is not correct. 
---
If creating a new …
> bug:popover - targetRef should be observed even when the popover is hidden

- website/src/pages/index.mdx
This pull request removes a link from the README.md file with a call to action that no longer applies since the Spectrum Community can no longer be joined.
> Documentation - Remove link to join Spectrum Community

- packages/tooltip/src/index.tsx
Hi there! 👋 Thanks for Reach UI!
I just wanted to add this types change which is necessary to use the exported `TriggerParams` generic type with `SVGSVGElement`, eg. when using the tooltip with an `<svg>` element as a child.
Without this change, TypeScript displays errors such as:
```
Type 'SVGSVGElement' does not satisfy the constraint 'HTMLElement'.
Type 'SVGSVGElement' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 20 more.ts(2344)
```
> [@reach/tooltip] Change types to also allow using SVG elements

- packages/combobox/src/index.tsx
Tiny fix to make the up arrow key behave the same that the down arrow key does when in IDLE state.
- [YES ] Use a meaningful title for the pull request. Include the name of the package modified.
- [YES] Test the change in your own code (Compile and run).
- [NA] Add or edit tests to reflect the change (Run with `yarn test`).
- [NA] Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- [YES] Ensure formatting is consistent with the project's Prettier configuration.
- [NA] Add documentation to support any new features.
This pull request: **Fixes a bug in an existing package**
**Not a new package.**
> Combobox: Up arrow in IDLE state now passes persistSelection to navigate, the same that down arrow does

- playground/stories/listbox.story.ts
- playground/stories/listbox/dynamic-content.example.tsx
These changes add an example to reproduce a bug that is fixed by https://github.com/reach/reach-ui/pull/827
I noticed a bug in the Listbox component when adding ListboxOptions dynamically to it. The keyboard selection order is scrambled. Luckily, there's an open PR to fix the bug.
To reproduce:
1. Navigate to new example in Storybook http://localhost:9001/?path=/story/listbox--dynamic-content-ts
2. Click two times on the "Add one more guest" button. This adds two more options to the listbox.
3. Click the listbox open, the "1 room" options should be selected
4. Press the "down arrow" key, I expected "2 rooms" to be selected, but instead "3 rooms" is selected.
Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help us process your request more …
> [listbox] add dynamic content example to reproduce bug with keyboard selection order.

- packages/descendants/src/index.tsx
---
I noticed when using the descendants package that `registerDescendant` is always getting called with a set index, never null. It looks to me as if the `set` method inside `registerDescendant` is meant to get `index === null` when a new element has been added and needs to be compared to its siblings in the DOM via `compareDocumentPosition`. Instead, the newest items all come in with `index: -1`, then get sorted to the front of the items array and treated as if they're the first descendants, even when they're not.
I admit that I wasn't able to properly build a test for this fix because I couldn't figure out how to set up the repo …
> Descendants: Fix a bug where new items get wrong index

- packages/visually-hidden/package.json
Hey team, right now if you install this package with a fresh React 18 project, you get a `ERESOLVE unable to resolve dependency tree` and I made this small change so that not everyone needs to do the whole `--legacy-peer-deps` thing.
I can update it to `>=16.8` instead of adding the `||` if you'd prefer, too, and add other packages as well, but I started small in case there might be a reason to not do this.
- Adds additional features/functionality to an existing package
> Add peer dependency for React 18 in `visually-hidden` package

- README.md
- package.json
As per https://github.com/reach/reach-ui/issues/952, `README.md` currently directs folks to install and build the project with `yarn`. The project moved to `pnpm` about four weeks ago, so contributors will trip up if they follow the installation instructions as is, or realize there's a `pnpm-lock.yaml` file and not trust the README at all.
I've swapped out `yarn` for `pnpm` where I can (and also replaced the `start` command with `dev` as well). However, the README also details a release process based on the old Lerna flow before moving to Turborepo. I'm not at all sure what the current release process is, so I'm leaving the PR as a draft until I get some feedback.
> Document use of pnpm/turbo in readme
