packages/menu-button/src/index.js

Make `onSelect` prop of `menu-button` required

---

packages/component-component/examples/lifecycles.example.js
packages/component-component/src/index.test.js

I noticed after running ESLint locally that there were three errors in the project, this PR fixes all of them :+1:

Fix remaining ESLint errors

---

packages/menu-button/src/index.js
www/src/pages/menu-button.mdx

Add `propTypes` for `menu-button` and update the associated documentation with a new `required` column for each prop.
Gets some way towards closing: #35 🎉

Prop types menu button

---

www/src/components/layout.js

Added target attribute to open Spectrum Community and GitHub links in new tab.

Opening external links in new tab

---

packages/alert/src/index.js
www/src/pages/alert.mdx

Another small PR but taking us even closer to closing #35! :tada:

Add propTypes and defaultProps to `Alert`

---

packages/window-size/index.d.ts

Takes us a little further towards our goal of closing: #37

Add TS types for `@reach/window-size`

---

packages/skip-nav/index.d.ts

Some more progress made on #37! :tada:

Add TS typings for @reach/skip-nav

---

packages/dialog/package.json
packages/dialog/src/__snapshots__/index.test.js.snap
packages/dialog/src/index.test.js

I've begun writing some tests for `Dialog`. Accommodating the portal may require workarounds (see https://github.com/facebook/react/issues/11565).

Begin dialog tests

---

packages/alert/index.d.ts

This PR continues the process of adding TypeScript declarations #37 🙂

Add TS declarations for alert package

---

packages/menu-button/examples/with-other-tabbables.example.js

Form elements must have labels :relaxed:

Form select must have label

---

packages/menu-button/index.d.ts

Add types for the menu-button: #37

Add TS types for @reach/menu-button

---

packages/menu-button/examples/render-callback.example.js
packages/menu-button/src/index.js
www/src/pages/menu-button.mdx

Add Render Callback to Menu

---

packages/menu-button/examples/non-menu-children.example.js
packages/menu-button/src/index.js

Add Support for Non menu-button Children

---

packages/component-component/src/__snapshots__/index.test.js.snap
packages/component-component/src/index.test.js

@ryanflorence, I wanted to go ahead and open this PR to get some feedback on what I've done so far. There are a few things that I am not real sure about at this point, and I don't wanna travel too far down a faulty path.
I'm not entirely sure how to approach testing the state changes or lifecycle function props using snapshots alone. I am definitely willing to keep going if you have some suggestions of how to assert that type of functionality from final renders.
Please let me know what you think, and I will adjust course as need be.

component-component tests

---

packages/dialog/package.json
packages/menu-button/package.json
yarn.lock

Carrying forward https://github.com/reach/reach-ui/pull/240, fixes #237
Follow the conversation here: https://github.com/reach/reach-ui/pull/240#issuecomment-520623449
Storybook is now working 👍

Add missing devDependencies for examples

---

www/src/pages/component-component.mdx

Fixes https://github.com/reach/reach-ui/issues/95

Update component-component didUpdate docs

---

packages/alert-dialog/package.json
packages/alert/package.json
packages/combobox/package.json
packages/component-component/package.json
packages/dialog/package.json
packages/menu-button/package.json
packages/rect/package.json
packages/tabs/package.json
packages/window-size/package.json

@mjackson fixed 🎉 
I made sure to only add `prop-types` to packages that use it

move prop-types to dependencies

---

packages/tooltip/src/index.js

onBlur was wrapping the onFocus callback

fixed onBlur wrapper

---

www/src/pages/rect.mdx

Hey, thank you for this library! 
Always use it in my projects and one small issue always confuses me :)
Actually child function should return something renderable

[Rect] (docs) Fix small documentation issue 

---

packages/alert-dialog/src/index.js

Mirrors the same in Dialog and allows things like `animated(AlertDialogOverlay)`

[AlertDialog] - forwardRef for AlertDialogOverlay/AlertDialogContent

---

www/src/pages/combobox.mdx

This pull request addresses issue #260 by providing documentation for the openOnFocus prop for the ComboBox package.

Added documentation for ComboBox openOnFocus prop to docs

---

www/src/components/layout.js

With this change, the copyright in the bottom left of the sidebar will reflect the current year.
I was scanning through your website, and noticed that your copyright was for last year. Thought it might help with a quick PR. This is super in-effective and calculates the year per render 😱🤔😉
---

Auto-renew the copyright year on the website

---

www/src/components/layout.js

This pull request adds a link in the docs on the left hand nav to the Portal page (issue #192).

Added link to portal page in the docs (issue #192)

---

packages/tooltip/examples/basic.example.js
packages/tooltip/src/index.js

tooltip: Pass through events and ref to the tooltip trigger

---

packages/window-size/examples/hook.example.js
packages/window-size/src/index.js
www/src/pages/window-size.mdx

Extracts WindowSize logic to make it available as a custom hook.

window-size: Extract to a new useWindowSize hook

---

packages/menu-button/examples/long-text.example.js
www/src/pages/funding.mdx
www/src/pages/index.mdx
www/src/pages/menu-button.mdx

Update links to React Training workshops + fix minor typos

---

packages/alert-dialog/index.d.ts
packages/alert-dialog/package.json
packages/alert/index.d.ts
packages/alert/package.json
packages/auto-id/package.json
packages/combobox/index.d.ts
packages/combobox/package.json
packages/dialog/index.d.ts
packages/dialog/package.json
packages/menu-button/index.d.ts
packages/menu-button/package.json
packages/popover/index.d.ts
packages/popover/package.json
packages/portal/index.d.ts
packages/portal/package.json
packages/rect/index.d.ts
packages/rect/package.json
packages/skip-nav/index.d.ts
packages/skip-nav/package.json
packages/slider/package.json
packages/tabs/index.d.ts
packages/tabs/package.json
packages/tooltip/index.d.ts
packages/tooltip/package.json
packages/visually-hidden/index.d.ts
packages/visually-hidden/package.json
packages/window-size/index.d.ts
packages/window-size/package.json

Add and include all package TS definitions

---

packages/menu-button/src/index.js

Revert "MenuButton: accept pass-through props on outer menu component"

---

website/src/pages/combobox.mdx

Add installation and import section to combobox docs

---

website/src/pages/combobox.mdx

This PR is a small change to the Combobox documentation that corrects `yarn add @reach/ombobox` to `yarn add @reach/combobox`

docs(combobox) Update incorrect package name

---

website/src/pages/dialog.mdx

Fix typo in Dialog docs

---

packages/portal/package.json
packages/portal/src/index.js

@reach/portal: Replace component-component with hooks

---

website/src/pages/dialog.mdx

Describe how to import styles in dialog's docs

---

website/src/pages/dialog.mdx

Add allowPinchZoom description for Dialog

[dialog] Add allowPinchZoom docs description

---

packages/combobox/src/index.tsx

[Combobox] Fix return type of ComboboxOptionText

---

website/src/pages/animation.mdx

Remove a double "the" from a sentence.

Remove double "the"

---

website/src/pages/tabs.mdx

Update incorrect custom TabPanel example

---

.codesandbox/ci.json
lerna.json
package.json
packages/accordion/package.json
packages/alert-dialog/package.json
packages/alert/package.json
packages/auto-id/package.json
packages/checkbox/package.json
packages/combobox/package.json
packages/dialog/package.json
packages/disclosure/package.json
packages/menu-button/package.json
packages/popover/package.json
packages/portal/package.json
packages/rect/package.json
packages/skip-nav/package.json
packages/slider/package.json
packages/tabs/package.json
packages/tooltip/package.json
packages/utils/package.json
packages/visually-hidden/package.json
packages/window-size/package.json
yarn.lock

You guys use `importHelpers` in your [tsconfig.json](https://github.com/reach/reach-ui/blob/master/tsconfig.build.json#L9). This add imports to `tslib` in your dist files:
ex: **visually-hidden.esm.js**
```js
import { __assign } from 'tslib';
import React, { forwardRef } from 'react';
/**
* Welcome to @reach/visually-hidden!
*/
```
Since this isn't a dep on any component It's possible to get build errors like this following:
```
[size......] › 🚒  error        Something went wrong building the master version of your package
ERROR in /private/var/folders/kd/4dz51_q566sg7y02l6gwc8zr9mjqwm/T/package-size-qxjfyq/node_modules/@reach/alert …
```

Add "tslib" add dep to all TS packages

---

packages/descendants/README.md
packages/descendants/src/index.tsx

Minor copy changes and updates to example code snippets to make things clearer. Was updating as I read along to learn about the new descendants package, I figured it was low-hanging to contribute the changes back.
Aside: the way `registerDescendant` works within the `DescendantProvider` is super interesting. I didn't even know [`compareDocumentPosition`](https://developer.mozilla.org/en-US/docs/Web/API/Node/compareDocumentPosition) existed.
https://github.com/reach/reach-ui/blob/3b55277a24116fbcc78f70d67f110f6259179f2d/packages/descendants/src/index.tsx#L87-L159
---
- ~[ ] Test the change in your own code (Compile and run).~ n/a
- ~[ ] Add or edit tests to reflect the change (Run with `yarn test`).~ n/a
- ~[ ] Add or edit Storybook examples to reflect the change (Run with `yarn start`).~ …

[Descendants] Update readme code snippets and comments

---

packages/combobox/src/index.tsx

Fix WAI-ARIA attributes in Combobox

---

packages/tabs/src/index.tsx

Fix a minor typo in Tabs comments

---

packages/tabs/examples/animated-bar.example.js

Super minor update to the animated Tabs example to center the selected tab underline 😅 
| Before | After |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/3409645/76915550-ef669e00-687a-11ea-83d0-4acd08e35020.png) | ![image](https://user-images.githubusercontent.com/3409645/76915502-cd6d1b80-687a-11ea-953c-32210113488f.png) |
---

[Tabs] Update animated example

---

packages/descendants/src/index.tsx

When reading through the descendants package, I noticed a `for` loop that is immediately overwritten by `filter`. This PR cleans that up.
-----

descendants: Remove unnecessary loop

---

packages/accordion/__tests__/accordion.test.tsx

[Accordion] User event and rendering tests

---

packages/dialog/__tests__/__snapshots__/dialog.test.tsx.snap
packages/dialog/__tests__/dialog.test.tsx

add test for dismiss dialog by clicking overlay

---

packages/dialog/examples/with-tooltip.example.js
packages/dialog/src/index.tsx

[dialog] Fixes #390: Disable tooltip when dialog closes

---

website/src/pages/animation.mdx
website/src/pages/dialog.mdx

[docs] Fix Modal Dialog Animation examples with Syntax Error

---

website/src/pages/listbox.mdx

- Spell `expanded` correctly
- Change `button` to `arrow` because this is the arrow example

Listbox docs: fix typos

---

packages/disclosure/__tests__/disclosure.test.tsx

Hello! I've seen https://github.com/reach/reach-ui/issues/508 and I want to contribute, I've added some tests to the `Disclosure` component, I'd love some feedback since I don't know what approach we want to follow in the new tests.
Also, I've been trying to make the keyboard tests works without any success, I'm not sure what we can do to make them work
___

Improve Disclosure component tests

---

packages/listbox/styles.css

Remove duplicate CSS declaration

---

packages/accordion/__tests__/accordion.test.tsx

I've added more tests to the `Accordion` component.
There are some things that I wasn't sure how to test, I've added some comments in the PR.
___

accordion: improve tests

---

packages/portal/src/index.tsx

Fix a comment in packages/portal

---

website/src/pages/dialog.mdx

[Dialog] Fix initialFocusRef docs by changing the prop heading to the DialogOverlay component

---

packages/dialog/examples/custom-focus-lock.example.tsx
packages/dialog/src/index.tsx

Add prop to dialog to bypass focus lock

---

packages/menu-button/src/index.tsx

[menu-button] Fixed popover closing when clicking outside

---

packages/descendants/README.md
packages/descendants/src/index.tsx

___
The README was incorrectly changed in https://github.com/reach/reach-ui/commit/714d70c442509cc72c4b18b656365d5fc7c2d174

[Descendants] Fix typo

---

packages/popover/src/index.tsx

Fix comment typo in Popover package

---

packages/visually-hidden/__tests__/visually-hidden.test.tsx
packages/visually-hidden/examples/basic.example.tsx
packages/visually-hidden/examples/with-as-prop.example.tsx
packages/visually-hidden/src/index.tsx
website/src/pages/visually-hidden.mdx

Add `as` property to VisuallyHidden

---

packages/alert/src/index.tsx

Change the root element of the hidden message to div

---

packages/slider/src/index.tsx

[slider] Fix #693 by capturing mutable value sliderRef.current

---

packages/tooltip/src/index.tsx

----
Fix for the issue https://github.com/reach/reach-ui/issues/738 introduced by my previous [PR](https://github.com/reach/reach-ui/pull/712)

fix(tooltip): prevent crashing when using SSR

---

packages/auto-id/src/index.tsx

fix(auto-id): add missing type overload

---

packages/accordion/package.json
packages/alert-dialog/package.json
packages/alert/package.json
packages/auto-id/package.json
packages/checkbox/package.json
packages/combobox/package.json
packages/component-component/package.json
packages/descendants/package.json
packages/dialog/package.json
packages/disclosure/package.json
packages/listbox/package.json
packages/machine/package.json
packages/menu-button/package.json
packages/popover/package.json
packages/portal/package.json
packages/rect/package.json
packages/skip-nav/package.json
packages/slider/package.json
packages/tabs/package.json
packages/tooltip/package.json
packages/utils/package.json
packages/utils/src/index.tsx
packages/visually-hidden/package.json
packages/window-size/package.json

Add sideEffects false to all packages to enable tree shaking

---

packages/tooltip/src/index.tsx

tooltip: Fix typo in comments

---

website/src/pages/animation.mdx

Docs: Add example check for CSS to respect a users anim prefs.

---

packages/dialog/src/index.tsx
website/src/pages/dialog.mdx

docs(dialog): fix typo

---

packages/auto-id/src/index.tsx

Fixed little typo in docs

---

packages/popover/examples/basic.example.js
packages/popover/examples/basic.example.tsx

The `width` property on the inner div of the Popover is preventing the programmatic width adjustments from ever happening.
| Before | After |
| :---: | :---: |
| ![before](https://user-images.githubusercontent.com/3409645/136616855-e7d770e1-0ab4-4989-b64c-93644f8d4efc.gif) | ![after](https://user-images.githubusercontent.com/3409645/136616860-7ef9bbfc-8170-4994-9dfd-f14649ea6ef4.gif) |

popover: fix position adjustment bugs in examples

---

packages/tabs/__tests__/tabs.test.tsx

[Tabs] Add test for manual keyboard navigation

---

website/src/pages/alert-dialog.mdx

Website: Fix missing TOC link for AlertDialogLabel

---

packages/descendants/README.md

docs: setter typo

---

website/src/pages/listbox.mdx

[website/listbox] Fix listbox code example
